"""updated_at-time-add

Revision ID: 0190d82153b2
Revises: 83f63f4f5efe
Create Date: 2025-12-02 22:30:02.551446

"""

from collections.abc import Sequence
from typing import Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0190d82153b2"
down_revision: Union[str, None] = "83f63f4f5efe"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "promotions",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("code", sa.String(length=50), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("description", sa.String(length=1000), nullable=True),
        sa.Column(
            "type",
            sa.Enum("discount_percent", "discount_fixed", "free_trial", "bonus_days", name="promotiontype"),
            nullable=False,
        ),
        sa.Column("value", sa.Integer(), nullable=False),
        sa.Column("valid_from", sa.DateTime(timezone=True), nullable=False),
        sa.Column("valid_until", sa.DateTime(timezone=True), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("max_uses", sa.Integer(), nullable=True),
        sa.Column("current_uses", sa.Integer(), nullable=False),
        sa.Column("applicable_plans", sa.JSON(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_promotions_code"), "promotions", ["code"], unique=True)
    op.create_index(op.f("ix_promotions_id"), "promotions", ["id"], unique=False)
    op.add_column(
        "subscription_plans",
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("subscription_plans", "updated_at")
    op.drop_index(op.f("ix_promotions_id"), table_name="promotions")
    op.drop_index(op.f("ix_promotions_code"), table_name="promotions")
    op.drop_table("promotions")
    # ### end Alembic commands ###
