"""payment table

Revision ID: 0c2cbc0978d4
Revises: 0190d82153b2
Create Date: 2025-12-06 01:41:03.108020

"""

from collections.abc import Sequence
from typing import Union

# revision identifiers, used by Alembic.
revision: str = "0c2cbc0978d4"
down_revision: Union[str, None] = "0190d82153b2"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
