"""latest_version

Revision ID: 65905bba8a82
Revises: dc3eaf6e5eb1
Create Date: 2025-12-19 01:18:51.873032

"""

from collections.abc import Sequence
from typing import Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "65905bba8a82"
down_revision: Union[str, None] = "dc3eaf6e5eb1"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "promotions",
        "type",
        existing_type=postgresql.ENUM(
            "discount_percent", "discount_fixed", "free_trial", "bonus_days", name="promotiontype"
        ),
        type_=sa.String(length=50),
        existing_nullable=False,
    )
    op.drop_column("promotions", "applicable_plans")
    op.drop_column("promotions", "value")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("promotions", sa.Column("value", sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column(
        "promotions",
        sa.Column("applicable_plans", postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    )
    op.alter_column(
        "promotions",
        "type",
        existing_type=sa.String(length=50),
        type_=postgresql.ENUM("discount_percent", "discount_fixed", "free_trial", "bonus_days", name="promotiontype"),
        existing_nullable=False,
    )
    # ### end Alembic commands ###
