"""change to string type

Revision ID: 88dd95820c31
Revises: b136d688840b
Create Date: 2025-12-15 23:46:46.120480

"""

from collections.abc import Sequence
from typing import Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "88dd95820c31"
down_revision: Union[str, None] = "b136d688840b"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "subscriptions",
        "status",
        existing_type=postgresql.ENUM("active", "cancelled", "expired", name="subscriptionstatus"),
        type_=sa.String(),
        existing_nullable=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "subscriptions",
        "status",
        existing_type=sa.String(),
        type_=postgresql.ENUM("active", "cancelled", "expired", name="subscriptionstatus"),
        existing_nullable=False,
    )
    # ### end Alembic commands ###
