"""new type of enum

Revision ID: 90cbb9e3aa6d
Revises: 88c903c42a53
Create Date: 2025-12-15 22:46:31.705654

"""

from collections.abc import Sequence
from typing import Union

# revision identifiers, used by Alembic.
revision: str = "90cbb9e3aa6d"
down_revision: Union[str, None] = "88c903c42a53"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
