"""pending type

Revision ID: b136d688840b
Revises: 90cbb9e3aa6d
Create Date: 2025-12-15 22:54:58.630259

"""

from collections.abc import Sequence
from typing import Union

# revision identifiers, used by Alembic.
revision: str = "b136d688840b"
down_revision: Union[str, None] = "90cbb9e3aa6d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
