"""delete default status

Revision ID: dc3eaf6e5eb1
Revises: 88dd95820c31
Create Date: 2025-12-15 23:48:29.627484

"""

from collections.abc import Sequence
from typing import Union

# revision identifiers, used by Alembic.
revision: str = "dc3eaf6e5eb1"
down_revision: Union[str, None] = "88dd95820c31"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
